import { readFileSync } from "node:fs";
import { join } from "node:path";

export interface BoardConfig {
  workOrders: { boardId: string; columnIds: Record<string, string> };
  deals: { boardId: string; columnIds: Record<string, string> };
}

let cached: BoardConfig | null = null;

/**
 * Board/column id map generated by `npm run import:monday` (scripts/import-to-monday.ts).
 * Keyed by the original CSV header string, e.g. columnIds["Execution Status"].
 * No secrets in this file — safe to commit, unlike .env.
 */
export function getBoardConfig(): BoardConfig {
  // Re-read in dev so board-config.json edits (e.g. after re-pointing board ids)
  // take effect without restarting the server.
  if (cached && process.env.NODE_ENV === "production") return cached;

  const path = join(process.cwd(), "lib", "monday", "board-config.json");
  try {
    cached = JSON.parse(readFileSync(path, "utf-8")) as BoardConfig;
  } catch {
    throw new Error(
      "lib/monday/board-config.json not found. Run `npm run import:monday` first (see doc/phase.md Phase 0)."
    );
  }
  return cached;
}
