import { gql } from "graphql-request";
import { getMondayClient } from "@/lib/monday/client";
import { flattenItem, type FlatMondayItem, type MondayBoardItemsPage } from "@/lib/monday/types";

// Configurable rather than hardcoded — monday.com's complexity budget is sensitive
// to page size (see doc/decision-log.md for the rate-limit failure this caused
// during the initial import). Defaults to 100, monday.com's own typical max.
export const MONDAY_PAGE_SIZE = Number(process.env.MONDAY_PAGE_SIZE ?? 100);

// Read-only query. Paginates via items_page cursor since monday.com boards
// can exceed a single page's item limit.
const BOARD_ITEMS_QUERY = gql`
  query BoardItems($boardId: ID!, $cursor: String, $limit: Int!) {
    boards(ids: [$boardId]) {
      items_page(limit: $limit, cursor: $cursor) {
        cursor
        items {
          id
          name
          column_values {
            id
            text
            type
          }
        }
      }
    }
  }
`;

/**
 * Pulls every item off a monday.com board, following pagination cursors.
 * boardId comes from lib/monday/board-config.json, generated by
 * scripts/import-to-monday.ts (see doc/phase.md Phase 0).
 */
export async function fetchAllBoardItems(boardId: string): Promise<FlatMondayItem[]> {
  const client = getMondayClient();
  const items: FlatMondayItem[] = [];
  let cursor: string | null = null;

  do {
    const response: MondayBoardItemsPage = await client.request(BOARD_ITEMS_QUERY, {
      boardId,
      cursor,
      limit: MONDAY_PAGE_SIZE,
    });

    const page = response.boards[0]?.items_page;
    if (!page) break;

    items.push(...page.items.map(flattenItem));
    cursor = page.cursor;
  } while (cursor);

  return items;
}
