import { gte, sql } from "drizzle-orm";
import { db } from "@/lib/db/client";
import { deals, workOrders, syncRuns } from "@/lib/db/schema";
import { fetchAllBoardItems } from "@/lib/monday/queries";
import { getBoardConfig } from "@/lib/monday/board-config";
import { normalizeDate } from "@/lib/normalize/dates";
import { normalizeSector } from "@/lib/normalize/sectors";
import { normalizeText } from "@/lib/normalize/text";
import { isHeaderEchoRow } from "@/lib/normalize/validity";
import type { FlatMondayItem } from "@/lib/monday/types";

// Logical field -> original CSV header, resolved to a monday column id via
// board-config.json (generated by scripts/import-to-monday.ts) at sync time.
const DEAL_FIELDS = {
  stage: "Deal Stage",
  sector: "Sector/service",
  value: "Masked Deal value",
  closeDate: "Close Date (A)",
  dealName: "Deal Name",
};

const WORK_ORDER_FIELDS = {
  status: "Execution Status",
  sector: "Sector",
  startDate: "Probable Start Date",
  dueDate: "Probable End Date",
  dealName: "Deal name masked",
};

function toDealRow(item: FlatMondayItem, columnIds: Record<string, string>, syncedAt: Date) {
  const rawSector = item.columns[columnIds[DEAL_FIELDS.sector]] ?? null;
  const { canonical, matched } = normalizeSector(rawSector);
  const closeDate = normalizeDate(item.columns[columnIds[DEAL_FIELDS.closeDate]]);
  const dealName = normalizeText(item.columns[columnIds[DEAL_FIELDS.dealName]] ?? item.name);
  const rawValue = item.columns[columnIds[DEAL_FIELDS.value]];
  const value = rawValue ? Number(rawValue.replace(/[^0-9.-]/g, "")) : null;
  const rawStage = item.columns[columnIds[DEAL_FIELDS.stage]] ?? null;

  const isIncomplete = !matched || !closeDate || !dealName || value === null || Number.isNaN(value);

  return {
    id: item.id,
    name: item.name,
    stage: rawStage,
    rawStage,
    sector: canonical,
    rawSector,
    value: value !== null && !Number.isNaN(value) ? String(value) : null,
    closeDate,
    dealName,
    isIncomplete,
    raw: item.columns,
    syncedAt,
  };
}

function toWorkOrderRow(item: FlatMondayItem, columnIds: Record<string, string>, syncedAt: Date) {
  const rawSector = item.columns[columnIds[WORK_ORDER_FIELDS.sector]] ?? null;
  const { canonical, matched } = normalizeSector(rawSector);
  const startDate = normalizeDate(item.columns[columnIds[WORK_ORDER_FIELDS.startDate]]);
  const dueDate = normalizeDate(item.columns[columnIds[WORK_ORDER_FIELDS.dueDate]]);
  const dealName = normalizeText(item.columns[columnIds[WORK_ORDER_FIELDS.dealName]]);
  const rawStatus = item.columns[columnIds[WORK_ORDER_FIELDS.status]] ?? null;

  const isIncomplete = !matched || !dueDate || !dealName;

  return {
    id: item.id,
    name: item.name,
    status: rawStatus,
    rawStatus,
    sector: canonical,
    rawSector,
    startDate,
    dueDate,
    dealName,
    isIncomplete,
    raw: item.columns,
    syncedAt,
  };
}

export interface SyncSummary {
  startedAt: string;
  finishedAt: string;
  rowsUpserted: number;
  rowsSkipped: number;
  errors: string[];
}

export async function runSync(): Promise<SyncSummary> {
  const startedAt = new Date();
  const errors: string[] = [];
  let rowsUpserted = 0;
  let rowsSkipped = 0;

  const boardConfig = getBoardConfig();

  try {
    const dealItems = await fetchAllBoardItems(boardConfig.deals.boardId);
    const validItems = dealItems.filter((item) => !isHeaderEchoRow(item.columns));
    rowsSkipped += dealItems.length - validItems.length;

    const dealRows = validItems.map((item) =>
      toDealRow(item, boardConfig.deals.columnIds, startedAt)
    );
    if (dealRows.length > 0) {
      await db
        .insert(deals)
        .values(dealRows)
        .onConflictDoUpdate({
          target: deals.id,
          set: {
            name: sql`excluded.name`,
            stage: sql`excluded.stage`,
            rawStage: sql`excluded.raw_stage`,
            sector: sql`excluded.sector`,
            rawSector: sql`excluded.raw_sector`,
            value: sql`excluded.value`,
            closeDate: sql`excluded.close_date`,
            dealName: sql`excluded.deal_name`,
            isIncomplete: sql`excluded.is_incomplete`,
            raw: sql`excluded.raw`,
            syncedAt: sql`excluded.synced_at`,
          },
        });
      rowsUpserted += dealRows.length;
    }
  } catch (err) {
    errors.push(`Deals sync failed: ${err instanceof Error ? err.message : String(err)}`);
  }

  try {
    const workOrderItems = await fetchAllBoardItems(boardConfig.workOrders.boardId);
    const validItems = workOrderItems.filter((item) => !isHeaderEchoRow(item.columns));
    rowsSkipped += workOrderItems.length - validItems.length;

    const workOrderRows = validItems.map((item) =>
      toWorkOrderRow(item, boardConfig.workOrders.columnIds, startedAt)
    );
    if (workOrderRows.length > 0) {
      await db
        .insert(workOrders)
        .values(workOrderRows)
        .onConflictDoUpdate({
          target: workOrders.id,
          set: {
            name: sql`excluded.name`,
            status: sql`excluded.status`,
            rawStatus: sql`excluded.raw_status`,
            sector: sql`excluded.sector`,
            rawSector: sql`excluded.raw_sector`,
            startDate: sql`excluded.start_date`,
            dueDate: sql`excluded.due_date`,
            dealName: sql`excluded.deal_name`,
            isIncomplete: sql`excluded.is_incomplete`,
            raw: sql`excluded.raw`,
            syncedAt: sql`excluded.synced_at`,
          },
        });
      rowsUpserted += workOrderRows.length;
    }
  } catch (err) {
    errors.push(`Work Orders sync failed: ${err instanceof Error ? err.message : String(err)}`);
  }

  const finishedAt = new Date();

  await db.insert(syncRuns).values({
    startedAt,
    finishedAt,
    boardsSynced: ["deals", "work_orders"],
    rowsUpserted: String(rowsUpserted),
    rowsSkipped: String(rowsSkipped),
    errors: errors.length > 0 ? errors : null,
  });

  return {
    startedAt: startedAt.toISOString(),
    finishedAt: finishedAt.toISOString(),
    rowsUpserted,
    rowsSkipped,
    errors,
  };
}

const SYNC_RATE_LIMIT = Number(process.env.MONDAY_SYNC_RATE_LIMIT ?? 100);
const SYNC_RATE_WINDOW_MS = 24 * 60 * 60 * 1000; // 24h — a sync-trigger endpoint has
// no reason to be hit faster than that; backed by sync_runs (not in-memory) so it
// holds up across serverless invocations, per doc/rule.md §6's rate-limiting rule.

export interface RateLimitCheck {
  allowed: boolean;
  recentSyncCount: number;
  limit: number;
}

export async function checkSyncRateLimit(): Promise<RateLimitCheck> {
  const windowStart = new Date(Date.now() - SYNC_RATE_WINDOW_MS);
  const rows = await db
    .select({ count: sql<number>`count(*)` })
    .from(syncRuns)
    .where(gte(syncRuns.startedAt, windowStart));

  const recentSyncCount = Number(rows[0]?.count ?? 0);
  return {
    allowed: recentSyncCount < SYNC_RATE_LIMIT,
    recentSyncCount,
    limit: SYNC_RATE_LIMIT,
  };
}
